name: Create Ubuntu and Windows Releases

on:
  push:
    tags:
    - '*'

  workflow_dispatch:

jobs:
  build-linux:

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: docker pull ghcr.io/xlightssequencer/xlights-build-docker:master
      - run: docker run --name buildvm ghcr.io/xlightssequencer/xlights-build-docker:master /bin/bash Recipe.xSchedule.appimage
      - run: 'docker cp buildvm:/xSchedule/xSchedule/AppImage/ /tmp/'
      - run: ls -lh /tmp/AppImage

      - uses: ncipollo/release-action@v1
        with:
           allowUpdates: true
           artifacts: "/tmp/AppImage/*.AppImage"
           token: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
   runs-on: windows-2022

   steps:
    - name: Checkout xSchedule
      uses: actions/checkout@v4
      with:
          submodules: 'recursive'

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Download wxWidgets
      run:
        git clone --depth=1 --shallow-submodules --recurse-submodules -b xlights_2026.04 https://github.com/xLightsSequencer/wxWidgets ..\wxWidgets\

    - name: Build wxWidgets
      working-directory: ..\wxWidgets\
      run: msbuild /m .\build\msw\wx_vc17.sln /p:Configuration="Release" /p:Platform="x64"

    - name: Build xSchedule
      shell: cmd
      working-directory: build_scripts\msw
      run: call build_xSchedule_x64.cmd

    - name: Build Installer
      working-directory: build_scripts\msw
      run: ISCC.exe xSchedule_64bit.iss

    - uses: ncipollo/release-action@v1
      with:
           allowUpdates: true
           artifacts: 'build_scripts\msw\output\*'
           token: ${{ secrets.GITHUB_TOKEN }}
