name: Windows xSchedule CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout xSchedule
      uses: actions/checkout@v4
      with:
          submodules: 'recursive'
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Download wxWidgets
      run:
        git clone --depth=1 --shallow-submodules --recurse-submodules -b xlights_2026.04 https://github.com/xLightsSequencer/wxWidgets ..\wxWidgets\

    - name: Build wxWidgets
      working-directory: ..\wxWidgets\
      run: msbuild /m .\build\msw\wx_vc17.sln /p:Configuration="Release" /p:Platform="x64"

    - name: Build xSchedule
      working-directory: xSchedule
      run: msbuild /m:10 xSchedule.sln /p:Configuration="Release" -p:Platform="x64"

    - name: Upload xSchedule Exe
      uses: actions/upload-artifact@v4
      with:
        name: xSchedule_Exe
        path: 'xSchedule\x64\Release\xSchedule.exe'
