name: Windows Nightly

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  check_for_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check for new commits today
        id: check-new-commits
        uses: adriangl/check-new-commits-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          seconds: 86400
          branch: 'main'
      - name: Set output if new commits found
        if: ${{ steps.check-new-commits.outputs.has-new-commits == 'true' }}
        run: echo "::set-output name=should_run::true"
      - name: Set output if no new commits
        if: ${{ steps.check-new-commits.outputs.has-new-commits != 'true' }}
        run: echo "::set-output name=should_run::false"
    outputs:
      should_run: ${{ steps.check-new-commits.outputs.has-new-commits }}

  build:
    needs: check_for_commits
    if: ${{ needs.check_for_commits.outputs.should_run == 'true' }}
    runs-on: windows-2022
    steps:
    - name: Checkout xSchedule
      uses: actions/checkout@v4
      with:
          submodules: 'recursive'
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Download wxWidgets
      run:
        git clone --depth=1 --shallow-submodules --recurse-submodules -b xlights_2026.04 https://github.com/xLightsSequencer/wxWidgets ..\wxWidgets\
    - name: Build wxWidgets
      working-directory: ..\wxWidgets\
      run: msbuild /m .\build\msw\wx_vc17.sln /p:Configuration="Release" /p:Platform="x64"
    - name: Build xSchedule
      shell: cmd
      working-directory: build_scripts\msw
      run: call build_xSchedule_x64.cmd
    - name: Build Installer
      working-directory: build_scripts\msw
      run: ISCC.exe xSchedule_64bit.iss
    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: xSchedule_x64_Installer
        path: 'build_scripts\msw\output\**'
    - name: Create prerelease
      if: github.ref == 'refs/heads/main'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: "nightly"
        title: "xSchedule Nightly"
        files: |
          ./build_scripts/msw/output/*.exe
